run:
  timeout: 2m

linters:
  enable:
    - revive
    - govet
    - gofumpt
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - typecheck

linters-settings:
  revive:
    rules:
      - name: exported
      - name: comment-spacings
